apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-memory-check
spec:
  template:
    spec:
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: gpu-memory-check
        image: gcr.io/lagorgeous-helping-hands/hamer:latest
        command: ["nvidia-smi"]
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 1
