apiVersion: batch/v1
kind: Job
metadata:
  name: hamer-render
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      # No nodeSelector for GPU-pool, as this job is CPU-bound
      containers:
      - name: hamer-render
        image: gcr.io/lagorgeous-helping-hands/hamer:latest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - /bin/sh
        - -c
        - "mkdir -p /mnt/nfs/rendered_outputs && python render.py --inference_input_folder /mnt/nfs/inference_outputs --output_folder /mnt/nfs/rendered_outputs --full_frame --side_view --save_mesh 2>&1 | tee /mnt/nfs/jobs/hamer-render/${POD_NAME}.log" # Command to run render.py
        
        volumeMounts:
        - name: nfs-storage
          mountPath: /mnt/nfs
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: filestore-pvc
      restartPolicy: OnFailure
